<!-- This is for the HTML validator -->
	<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<!-- The real code begins here -->

<?php
# Copyright (C) 2007 - Paul Zastoupil, Reinier Post, Marko Lindqvist
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

  // include the php-code finder
  ini_set("include_path",
	ini_get("include_path") . ":" . $_SERVER["DOCUMENT_ROOT"]
  );
  include_once("php_code/settings.php");
  include_once("php_code/php_code_find.php");
  // includes for support routines
  include_once(php_code_find("fcdb.php"));
  include_once(php_code_find("polls.php"));
  include_once(php_code_find("img.php"));
?>

<HTML>
<HEAD>
<TITLE>Old Freeciv Polls</TITLE>
<META HTTP-EQUIV=Content-Language CONTENT=en>
</HEAD>

<BODY BGCOLOR="#FFFAF0">

<CENTER>

<?
img_html("headers/oldpolls.gif", "Old Polls", NULL, NULL);
?>

</CENTER>

<BR>
<CENTER>
<?php polls_emit_old_polls(); ?>
</CENTER>
<BR>

<BR>
<HR>Return to <a href="/">the main page</A>
<HR>In case of technical problems, please contact
<?php echo $webmaster_html ?>.

<BR><BR>
<P ALIGN="center">
<?
img_html("hr.gif", "--------", NULL, NULL);
?>
</P>
<BR><BR>

</BODY>
</HTML>
