#!/bin/sh

# Copyright (C) 2014 - Marko Lindqvist
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.

if test "x$1" = "x" || test "x$1" = "x-h" || test "x$1" = "x--help" ; then
  echo "Usage: $0 <flags spec file>"
  exit
fi

if ! test -f "$1" ; then
  echo "Flag spec \"$1\" not found" >&2
  exit 1
fi

(
echo "<?php";
echo "/* This file is autogenerated by private/build_flagspec.sh from"
echo " * freeciv metaserver repository. */"
echo "\$flags = array(";

cat $1 | grep "\".*\".*,.*\".*\"" | grep -v ";.*\"" | grep -v "\"tag\"" | sed 's/;.*//' | sed -e 's/,/ => /' -e "s/\"[:space:\t ]*\$/.png\",/" -e "s/\"/'/g" -e "s,flags/,,"

echo "'unknown' => 'unknown.png');";
echo "?>";
) > ../php_code/flagspecs.php
